version: '3.2'
services:
  db:
    image: postgres:10

  web:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
      - bundle_cache:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    command:
      - ./run-from-container.sh

volumes:
  bundle_cache:
